# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{soap-lc}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gr\303\251goire Lejeune"]
  s.date = %q{2010-02-10}
  s.description = %q{SOAP Lite Client provides support for developing clients interfaces from WSDL files.}
  s.email = %q{gregoire.lejeune@free.fr}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "examples/mono/NumberService.asmx",
     "examples/mono/README.txt",
     "examples/mono/index.html",
     "lib/soap/lc.rb",
     "lib/soap/lc/core_ext.rb",
     "lib/soap/lc/error.rb",
     "lib/soap/lc/request.rb",
     "lib/soap/lc/response.rb",
     "lib/soap/lc/version.rb",
     "lib/soap/lc/wsdl.rb",
     "lib/soap/lc/wsdl/binding.rb",
     "lib/soap/lc/wsdl/message.rb",
     "lib/soap/lc/wsdl/parser.rb",
     "lib/soap/lc/wsdl/portType.rb",
     "lib/soap/lc/wsdl/service.rb",
     "lib/soap/lc/xsd.rb",
     "lib/soap/lc/xsd/complextype.rb",
     "lib/soap/lc/xsd/convert.rb",
     "lib/soap/lc/xsd/element.rb",
     "lib/soap/lc/xsd/enumeration.rb",
     "lib/soap/lc/xsd/restriction.rb",
     "lib/soap/lc/xsd/sequence.rb",
     "lib/soap/lc/xsd/simpletype.rb",
     "soap-lc.gemspec",
     "tests/t_000.rb"
  ]
  s.homepage = %q{http://github.com/glejeune/soap-lc}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{SOAP Lite Client provides support for developing clients interfaces from WSDL files.}
  s.test_files = [
    "examples/NEVER_COMMIT/t_000.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
  end
end

